name: build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake protobuf-compiler libprotobuf-dev libgflags-dev nlohmann-json3-dev
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release -- -j$(nproc)
      - name: Run tests
        run: ctest --test-dir build --output-on-failure || true  # remove `|| true` if you have tests
